// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWqA_wXad0PtZw24vO7gj4mj91B2eJv8',
    appId: '1:796822266355:web:b86c0e9448314883aeb286',
    messagingSenderId: '796822266355',
    projectId: 'slsp-a88d6',
    authDomain: 'slsp-a88d6.firebaseapp.com',
    databaseURL: 'https://slsp-a88d6-default-rtdb.firebaseio.com',
    storageBucket: 'slsp-a88d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZv7JCQ4D-ielRfkTL0N0JxMDoyFMUY8',
    appId: '1:796822266355:android:faf5ebd9483fed10aeb286',
    messagingSenderId: '796822266355',
    projectId: 'slsp-a88d6',
    databaseURL: 'https://slsp-a88d6-default-rtdb.firebaseio.com',
    storageBucket: 'slsp-a88d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd47TQVoTeO2O8JFJueZeCTgQeYieqMOc',
    appId: '1:796822266355:ios:ab9acec195af3624aeb286',
    messagingSenderId: '796822266355',
    projectId: 'slsp-a88d6',
    databaseURL: 'https://slsp-a88d6-default-rtdb.firebaseio.com',
    storageBucket: 'slsp-a88d6.appspot.com',
    iosBundleId: 'com.example.slsMvpMicrosoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd47TQVoTeO2O8JFJueZeCTgQeYieqMOc',
    appId: '1:796822266355:ios:38e01c4598184202aeb286',
    messagingSenderId: '796822266355',
    projectId: 'slsp-a88d6',
    databaseURL: 'https://slsp-a88d6-default-rtdb.firebaseio.com',
    storageBucket: 'slsp-a88d6.appspot.com',
    iosBundleId: 'com.example.slsMvpMicrosoft.RunnerTests',
  );
}
